# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.arosehale@github.io
title: Amanda Rose Hale
email: amandarhale@gmail.com
author: Amanda Hale
description: "Amanda's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://github.com/arosehale  
  - icon: envelope-o
    title: email
    url: mailto:amandarhale@gmail.com
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/amandarosehale 
  - icon: file-pdf-o
    title: CV
    url: img/CassolDanielaCV.pdf
#  - icon: website
#    title: CV Lattes
#    url: http://lattes.cnpq.br/5399100590606067
  - icon: twitter
    title: twitter
    url: https://twitter.com/amandarosehale

